### ISSUE TITLE
Whole app Refactoring

### ISSUE THREAD

**Issue by cassioscabral** [cassioscabral/rateissuesfront#15]
We need to clean the code for the next changes.

The refactoring must focus on cleaning the code using lint, jscs and editor config.
- [x] add new rules to linters(react es lint, jscs, editorconfig)
- [x] material-ui is not being used(was used for icons) anymore and the code that was using them are commented. Find a replacement for icons that don't require too much dependencies to use it and change them.
- [x] remove warnings/errors using the editor plugin
- [x] remove React warnings on browser console
- [x] clean the code removing unnecessary comments 
- [x] refactor the code to ES6 like changing vars to let
- [x] components or HTML elements with too much attributes must be reorganized in one attribute by line for better readability

**Comment by cassioscabral** [comment]
Lint rules

prefer-es6-class: Enforce ES5 or ES6 class for React Components

jsx-curly-spacing: Enforce or disallow spaces inside of curly braces in JSX attributes (fixable)
  1 space, always

jsx-first-prop-new-line: Enforce position of the first prop in JSX

jsx-indent: Validate JSX indentation
  2 spaces

jsx-indent-props: Validate props indentation in JSX (fixable)
  2 spaces

jsx-max-props-per-line: Limit maximum of props on a single line in JSX
  1

jsx-pascal-case: Enforce PascalCase for user-defined JSX components

jsx-space-before-closing: Validate spacing before closing bracket in JSX (fixable)

**Comment by EdikoCruz** [comment]
clean the code removing unnecessary comments #22
